### ISSUE TITLE
Change "First day of week"

### ISSUE THREAD

**Issue by barnumbirr** [revelationnow/PlannerPDF#3]
Hey there,

thanks a lot for this project 🎉 I've been using the resulting PDF ever since I got my RM2 a couple of weeks ago. One thing I'd possibly change would be the ability to pass a "first day of week" as a `cmake` option.

Cheers.

**Comment by revelationnow** [comment]
Yes, I've been planning to add that, let me prioritize it now. Hopefully will find some time today to do that and a few other options I was planning on adding.

**Comment by revelationnow** [comment]
Latest commit adds that option.
